version: '3'
services:
  webserver:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - database

  php:
    image: php:7.4-fpm
    volumes:
      - ./public:/var/www/html
    depends_on:
      - database
    environment:
      - PHP_EXTENSIONS=mysqli
    command: php-fpm --allow-to-run-as-root

  database:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spacerunner
      - MYSQL_DATABASE=spacerunner
      - MYSQL_USER=spacerunner
      - MYSQL_PASSWORD=spacerunner