version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
    depends_on:
      - php
    networks:
      - lemp_network

  php:
    image: php:latest
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./public:/var/www/html
    networks:
      - lemp_network

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - lemp_network

networks:
  lemp_network:
