version: '3'
services:
  webserver:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./public:/var/www/html
    depends_on:
      - database

  database:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spacerunner
      - MYSQL_DATABASE=spacerunner
      - MYSQL_USER=spacerunner
      - MYSQL_PASSWORD=spacerunner
