version: '3'
services:
  webserver:
    container_name: docker-lemp-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - database

  php:
    container_name: docker-lemp-php
    image: php:7.4-fpm
    volumes:
      - ./public:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database

  database:
    container_name: docker-lemp-mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spacerunner
      - MYSQL_DATABASE=spacerunner
      - MYSQL_USER=spacerunner
      - MYSQL_PASSWORD=spacerunner
